# Generated by Django 5.1.8 on 2025-04-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
        ('users', '0002_alter_userprofile_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='books',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.book'),
        ),
    ]
